/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package checkbox.vista;

import checkbox.logica.Persona;
import checkbox.logica.PoolPersonas;
import javax.swing.JOptionPane;

/**
 *
 * @author dual
 */
public class ModificarPersona extends javax.swing.JFrame {

    private final PoolPersonas poolPersonas = new PoolPersonas();
    /**
     * Creates new form ModificarPersona
     */
    public ModificarPersona() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1Aceptar = new javax.swing.JButton();
        jButton2Limpiar = new javax.swing.JButton();
        jButton3Salir = new javax.swing.JButton();
        jTextField1Nif = new javax.swing.JTextField();
        jLabel1estado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2Nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3Apellidos = new javax.swing.JTextField();
        jComboBox1Sexe = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel1estado1 = new javax.swing.JLabel();
        jButtonAlta = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonConsulta = new javax.swing.JButton();
        jButtonModificacion = new javax.swing.JButton();
        jComboBox1Estado = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        jButton1Aceptar.setText("Aceptar");
        jButton1Aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1AceptarMouseEntered(evt);
            }
        });
        jButton1Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1AceptarActionPerformed(evt);
            }
        });

        jButton2Limpiar.setText("Limpiar");
        jButton2Limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2LimpiarMouseEntered(evt);
            }
        });
        jButton2Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2LimpiarActionPerformed(evt);
            }
        });

        jButton3Salir.setText("Salir");
        jButton3Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3SalirMouseEntered(evt);
            }
        });
        jButton3Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3SalirActionPerformed(evt);
            }
        });

        jTextField1Nif.setText("Introduce un NIF");
        jTextField1Nif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1NifActionPerformed(evt);
            }
        });

        jLabel1estado.setText("Sexe:");

        jLabel2.setText("Nombre:");

        jTextField2Nombre.setText("Introduce un nombre");
        jTextField2Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2NombreActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellidos:");

        jTextField3Apellidos.setText("Introduce un apellido");
        jTextField3Apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ApellidosActionPerformed(evt);
            }
        });

        jComboBox1Sexe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Home", "Dona" }));
        jComboBox1Sexe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1SexeActionPerformed(evt);
            }
        });

        jLabel4.setText("NIF:");

        jLabel1estado1.setText("Estado:");

        jButtonAlta.setText("ALTA");
        jButtonAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAltaMouseEntered(evt);
            }
        });
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("ELIMINAR");
        jButtonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonEliminarMouseEntered(evt);
            }
        });
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonConsulta.setText("CONSULTA");
        jButtonConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonConsultaMouseEntered(evt);
            }
        });
        jButtonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaActionPerformed(evt);
            }
        });

        jButtonModificacion.setText("MODIFICACION");
        jButtonModificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonModificacionMouseEntered(evt);
            }
        });
        jButtonModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificacionActionPerformed(evt);
            }
        });

        jComboBox1Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En atur", "Estudiant", "Treballador" }));

        jLabelInfo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelInfo.setForeground(new java.awt.Color(51, 51, 51));
        jLabelInfo.setText("Selecciona");
        jLabelInfo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(59, 59, 59)
                .addComponent(jTextField2Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButtonAlta))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(54, 54, 54)
                .addComponent(jTextField3Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButtonEliminar))
            .addGroup(layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jButtonModificacion))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addGap(79, 79, 79)
                .addComponent(jTextField1Nif, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButtonConsulta))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1estado)
                .addGap(72, 72, 72)
                .addComponent(jComboBox1Sexe, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1estado1)
                .addGap(63, 63, 63)
                .addComponent(jComboBox1Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1Aceptar)
                .addGap(49, 49, 49)
                .addComponent(jButton2Limpiar)
                .addGap(75, 75, 75)
                .addComponent(jButton3Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlta))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEliminar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextField3Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addComponent(jButtonModificacion)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1Nif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButtonConsulta)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1estado)
                    .addComponent(jComboBox1Sexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1estado1))
                    .addComponent(jComboBox1Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1Aceptar)
                    .addComponent(jButton2Limpiar)
                    .addComponent(jButton3Salir))
                .addGap(17, 17, 17)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Accion al pulsar el botón Limpiar.
     * @param evt 
     */
    private void jButton2LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2LimpiarActionPerformed
        jTextField1Nif.setText("");
        jTextField2Nombre.setText("");
        jTextField3Apellidos.setText("");
        jComboBox1Estado.setSelectedIndex(0);
        jComboBox1Sexe.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2LimpiarActionPerformed

    
    
    private void jTextField1NifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1NifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1NifActionPerformed

    /**
     * Acción al pulsar el boton aceptar.
     * @param evt 
     */
    private void jButton1AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AceptarActionPerformed
        
        String nie = jTextField1Nif.getText();
        String nombre = jTextField2Nombre.getText();
        String apellido = jTextField3Apellidos.getText();
        
        int sexe = jComboBox1Sexe.getSelectedIndex();
        int estado = jComboBox1Estado.getSelectedIndex();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Falta rellenar: nombre");
            return;
        } else if (apellido.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Falta rellenar: apellido");
            return;
        } else if (nie.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Falta rellenar: NIE");
            return;
        }
        
        Persona p = new Persona(nie);
        p.setNom(nombre);
        p.setApellido(apellido);
        
        if (sexe==0) {
            p.setSexe(Persona.Sexe.Home);
        } else {
            p.setSexe(Persona.Sexe.Dona);
        }
        switch (estado) {
            case 0:
                p.setEstado(Persona.Estado.Paro);
                break;
            case 1:
                p.setEstado(Persona.Estado.Estudiante);
                break;
            case 2:
                p.setEstado(Persona.Estado.Trabajador);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Falta rellenar: estado");
                return;
        }
        poolPersonas.addPersona(p);
        JOptionPane.showMessageDialog(this, "Se ha guardado la persona con NIE: "+p.getNie());
    }//GEN-LAST:event_jButton1AceptarActionPerformed

    private void jTextField2NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2NombreActionPerformed

    private void jTextField3ApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ApellidosActionPerformed

    /**
     * Accion al pulsar el botón Salir.
     * @param evt 
     */
    private void jButton3SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3SalirActionPerformed
        poolPersonas.guardarDatos();
        System.exit(0);
    }//GEN-LAST:event_jButton3SalirActionPerformed

    private void jComboBox1SexeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1SexeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1SexeActionPerformed

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        String msg = poolPersonas.alta(jTextField1Nif.getText());
        JOptionPane.showMessageDialog(this, msg);
    }//GEN-LAST:event_jButtonAltaActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        String msg = poolPersonas.eliminar(jTextField1Nif.getText());
        JOptionPane.showMessageDialog(this, msg);
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificacionActionPerformed
        String msg = poolPersonas.modificacion(jTextField1Nif.getText());
        JOptionPane.showMessageDialog(this, msg);
    }//GEN-LAST:event_jButtonModificacionActionPerformed

    private void jButtonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaActionPerformed
        Persona consulta = poolPersonas.consulta(jTextField1Nif.getText());
        if (consulta==null) JOptionPane.showMessageDialog(this, "Error");
        else {
            jTextField2Nombre.setText(consulta.getNom());
            jTextField3Apellidos.setText(consulta.getApellido());
        }
    }//GEN-LAST:event_jButtonConsultaActionPerformed

    private void jButtonAltaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAltaMouseEntered
        jLabelInfo.setText("Dar de alta al usuario con el DNI: "+jTextField1Nif.getText()+". Primero hay que añadir la persona con 'aceptar'.");
    }//GEN-LAST:event_jButtonAltaMouseEntered

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        jLabelInfo.setText("Selecciona");
    }//GEN-LAST:event_formMouseEntered

    private void jButtonEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEliminarMouseEntered
        jLabelInfo.setText("Eliminar el usuario con el DNI: "+jTextField1Nif.getText());
    }//GEN-LAST:event_jButtonEliminarMouseEntered

    private void jButtonModificacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonModificacionMouseEntered
        jLabelInfo.setText("Modificar los datos del usuario con el DNI:"+jTextField1Nif.getText());
    }//GEN-LAST:event_jButtonModificacionMouseEntered

    private void jButtonConsultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConsultaMouseEntered
        jLabelInfo.setText("Consultar los datos del usuario con el DNI: "+jTextField1Nif.getText());
    }//GEN-LAST:event_jButtonConsultaMouseEntered

    private void jButton2LimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2LimpiarMouseEntered
        jLabelInfo.setText("Vacía todos los campos para introducir otra persona.");
    }//GEN-LAST:event_jButton2LimpiarMouseEntered

    private void jButton1AceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1AceptarMouseEntered
        jLabelInfo.setText("Añade la persona.");
    }//GEN-LAST:event_jButton1AceptarMouseEntered

    private void jButton3SalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3SalirMouseEntered
        jLabelInfo.setText("Guarda las personas en un fichero y sale del programa.");
    }//GEN-LAST:event_jButton3SalirMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1Aceptar;
    private javax.swing.JButton jButton2Limpiar;
    private javax.swing.JButton jButton3Salir;
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonConsulta;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificacion;
    private javax.swing.JComboBox<String> jComboBox1Estado;
    private javax.swing.JComboBox<String> jComboBox1Sexe;
    private javax.swing.JLabel jLabel1estado;
    private javax.swing.JLabel jLabel1estado1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1Nif;
    private javax.swing.JTextField jTextField2Nombre;
    private javax.swing.JTextField jTextField3Apellidos;
    // End of variables declaration//GEN-END:variables
}
